# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Ns4kqvBd-kthj9uFgaTwffKkqYTh3fHF
"""

print('ola mundo!!!')

x1 = 6 + 4 * 2
x2 = (4 * 9 + 5)
x3 = ((6 + 7) * 9)
x4 = (15 + 20 - 30)
x5 = (6 +5**2)

print(x1, x2, x3, x4, x5)

numero_1 = 5
numero_1 += 5
print(numero_1)

x = 8
x += 5
print(x)
x -= 4
print(x)
x *= 20
print(x)
x/=2
print(x)

numero_ = 2
numero_2 = 4

soma = numero_1 + numero_2

if soma < 10 :
 print ("A soma e menor que 10")

X = 8
 print(x)
 x1 = 3
 print
 x_Result = X < x1
 X_Result = x == x1
 x_result = x >= x1
 xresult = x != x1

time_carlos  = "Botafogo"
time_luciano = "Flamengo"
time_fabricia = "botafogo"
print(time_carlos is time_luciano)

x  = "Botafogo"
x1 = "Flamengo"
x3= "Botafogo"

result = x is x3
print(result)
xresult = x is not x3
print(result)
xresult = x1 is x3
print(result)
xresult = x1 is not x3
print(result)

x = 4
x1 = 9
x2 = 5

 XResult = (((2 + 5) * 3) + X + 5) < x1
 XResult + (((2 + 5) * 3) + (X + 5 < X1) == ( X == 6 + X2 * 2))
 XResult = (((3 * 6) + X - 3) < X2)
 XResultad + (((7 * 8) > (X + 4 > X1) < ( X ! = 2 + X2 * 9)))

nota1 = float(input( " Digite a primeira nota: "))
nota2 = floa (input( " |Digite s segunda nota "))

# calcular a  media aritmedica
if media > (nota 1 + nota2)

a = int(input("informe um numero entre 0 e 100:"))
if a > 50:
  print(" o numero", a," e maior que 50")
  elif a == 50:
  print ("o numero informado e igual a 50")
 else:
 print ("o numero",a," e menor que 50")